#ifndef PHP_CLD2_ENCODINGS_H
#define PHP_CLD2_ENCODINGS_H

static const char *encodingStrings[] = {
        "ISO_8859_1",
        "ISO_8859_2",
        "ISO_8859_3",
        "ISO_8859_4",
        "ISO_8859_5",
        "ISO_8859_6",
        "ISO_8859_7",
        "ISO_8859_8",
        "ISO_8859_9",
        "ISO_8859_10",
        "JAPANESE_EUC_JP",
        "JAPANESE_SHIFT_JIS",
        "JAPANESE_JIS",
        "CHINESE_BIG5",
        "CHINESE_GB",
        "CHINESE_EUC_CN",
        "KOREAN_EUC_KR",
        "UNICODE_UNUSED",
        "CHINESE_EUC_DEC",
        "CHINESE_CNS",
        "CHINESE_BIG5_CP950",
        "JAPANESE_CP932",
        "UTF8",
        "UNKNOWN_ENCODING",
        "ASCII_7BIT",
        "RUSSIAN_KOI8_R",
        "RUSSIAN_CP1251",
        "MSFT_CP1252",
        "RUSSIAN_KOI8_RU",
        "MSFT_CP1250",
        "ISO_8859_15",
        "MSFT_CP1254",
        "MSFT_CP1257",
        "ISO_8859_11",
        "MSFT_CP874",
        "MSFT_CP1256",
        "MSFT_CP1255",
        "ISO_8859_8_I",
        "HEBREW_VISUAL",
        "CZECH_CP852",
        "CZECH_CSN_369103",
        "MSFT_CP1253",
        "RUSSIAN_CP866",
        "ISO_8859_13",
        "ISO_2022_KR",
        "GBK",
        "GB18030",
        "BIG5_HKSCS",
        "ISO_2022_CN",
        "TSCII",
        "TAMIL_MONO",
        "TAMIL_BI",
        "JAGRAN",
        "MACINTOSH_ROMAN",
        "UTF7",
        "BHASKAR",
        "HTCHANAKYA",
        "UTF16BE",
        "UTF16LE",
        "UTF32BE",
        "UTF32LE",
        "BINARYENC",
        "HZ_GB_2312",
        "UTF8UTF8",
        "TAM_ELANGO",
        "TAM_LTTMBARANI",
        "TAM_SHREE",
        "TAM_TBOOMIS",
        "TAM_TMNEWS",
        "TAM_WEBTAMIL",
        "KDDI_SHIFT_JIS",
        "DOCOMO_SHIFT_JIS",
        "SOFTBANK_SHIFT_JIS",
        "KDDI_ISO_2022_JP",
        "SOFTBANK_ISO_2022_JP",
};

#endif  // PHP_CLD2_ENCODINGS_H


